version: '2'
services:
  myapp:
    image: 'bitnami/codeigniter:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports: 
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /Users/markostojanovic/work/projects/time-zones/persistance:/bitnami/mariadb

